run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true
linters-settings:
  goimports:
    local-prefixes: github.com/calyptia/cloud
  revive:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
  misspell:
    locale: US
  gomnd:
    ignored-numbers:
      - 2 #used for word splitting.
  nolintlint:
    allow-leading-space: false # require machine-readable nolint directives (with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - depguard
    - dupl
    - exportloopref
    - forcetypeassert
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofumpt
    - revive
    - gomnd
    - goprintffuncname
    - gosec
    - ifshort
    - misspell
    - noctx
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - whitespace
issues:
  exclude-use-default: false
  exclude-rules:
  - linters:
     - funlen
     - stylecheck
     - gocyclo
     - gocognit
     - revive
     - dupl
     - goconst
     - errcheck
     - bodyclose
     - gomnd
     - thelper
    path: '.*test.*.go'
