name: Go

on:
  push:
    branches: [master, main]
    tags: [v*]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # TODO: Login to ghcr.io

      - uses: actions/checkout@v3

      # Required by golangci-lint-action@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2
  test:
    runs-on: ubuntu-latest
    steps:
      # TODO: Login to ghcr.io

      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        run: go test -v ./...
